name: Health Check
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "**.js"
      - "**.sol"

jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare | Checkout
        uses: actions/checkout@v4
      - name: Prepare | NPM install
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Prepare | Install packages
        run: npm ci
      - name: Test | Run coverage
        run: npm run test
